[project]
name = "text-to-speech"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "modal>=1.2.5",
    "pydantic>=2.12.5",
    "torch>=2.9.1",
    "torchaudio>=2.9.1",
]
